"""Disaster-simulator state and synthetic-incident generation (Phase 4).

Deliberately an in-memory singleton, NOT a database table: this is
presenter/demo control state for a single-worker dev server, not
operational data that needs to survive a restart or be shared across
processes. If Aasha Setu is ever run with multiple Uvicorn workers this must
move to Redis (already in the stack) — noted here, not built now, since a
single-worker demo doesn't need it.

The simulator feeds two of the risk engine's inputs (see
app/services/risk_zones.py): rainfall/water level raise effective hazard,
road blockage raises effective (in)accessibility. That's what makes
"START DISASTER" visibly move the risk map and, in turn, incident
severity — without needing a real IMD feed.
"""
import random
from dataclasses import asdict, dataclass, replace

from sqlalchemy.orm import Session

from app.events.broker import broker
from app.risk.demo_baseline import CHENNAI_DEMO_BBOX
from app.services import incidents as incidents_service


@dataclass(frozen=True)
class SimulatorState:
    active: bool = False
    rainfall_mm: float = 0.0  # 0-300
    water_level_m: float = 0.0  # 0-5
    road_blockage_pct: float = 0.0  # 0-100


_state = SimulatorState()

MAX_HAZARD_BOOST = 40.0
MAX_ACCESSIBILITY_BOOST = 30.0

SEVERITIES = ["low", "moderate", "high", "very_high", "critical"]


def get_state() -> SimulatorState:
    return _state


def set_state(
    *,
    active: bool | None = None,
    rainfall_mm: float | None = None,
    water_level_m: float | None = None,
    road_blockage_pct: float | None = None,
) -> SimulatorState:
    global _state
    updates = {
        k: v
        for k, v in {
            "active": active,
            "rainfall_mm": rainfall_mm,
            "water_level_m": water_level_m,
            "road_blockage_pct": road_blockage_pct,
        }.items()
        if v is not None
    }
    _state = replace(_state, **updates)
    # Single chokepoint for every simulator mutation (start/stop/patch all
    # route through here) — one place to emit the realtime event. The
    # simulator feeds the risk formula, so nudge the map too.
    broker.publish("simulator.updated", asdict(_state))
    broker.publish("risk.updated", {"reason": "simulator"})
    return _state


def start(rainfall_mm: float = 220.0, water_level_m: float = 3.5, road_blockage_pct: float = 40.0) -> SimulatorState:
    return set_state(
        active=True, rainfall_mm=rainfall_mm, water_level_m=water_level_m, road_blockage_pct=road_blockage_pct
    )


def stop() -> SimulatorState:
    return set_state(active=False, rainfall_mm=0.0, water_level_m=0.0, road_blockage_pct=0.0)


def hazard_boost() -> float:
    s = _state
    return min(MAX_HAZARD_BOOST, (s.rainfall_mm / 300) * 25 + (s.water_level_m / 5) * 15)


def accessibility_boost() -> float:
    return min(MAX_ACCESSIBILITY_BOOST, (_state.road_blockage_pct / 100) * MAX_ACCESSIBILITY_BOOST)


def _severity_weights() -> tuple[list[str], list[float]]:
    s = _state
    if not s.active:
        return (["low", "moderate"], [0.6, 0.4])
    intensity = min(1.0, ((s.rainfall_mm / 300) + (s.water_level_m / 5)) / 2)
    weights = {
        "low": max(0.05, 0.3 * (1 - intensity)),
        "moderate": 0.3,
        "high": 0.2 + 0.3 * intensity,
        "very_high": 0.1 + 0.2 * intensity,
        "critical": 0.05 + 0.3 * intensity,
    }
    return list(weights.keys()), list(weights.values())


def spawn_synthetic_incidents(db: Session, *, count: int, max_people_affected: int) -> list:
    """Generates `count` demo flood incidents scattered across the demo
    bounding box, with severity skewed toward the current simulator
    intensity. Always clearly labeled in the description — never
    indistinguishable from a genuine citizen report."""
    labels, weights = _severity_weights()
    bbox = CHENNAI_DEMO_BBOX
    created = []
    for _ in range(count):
        severity = random.choices(labels, weights=weights)[0]
        latitude = random.uniform(bbox.min_lat, bbox.max_lat)
        longitude = random.uniform(bbox.min_lon, bbox.max_lon)
        people_affected = random.randint(0, max_people_affected)
        incident = incidents_service.create_incident(
            db,
            reported_by=None,
            type_="flood",
            latitude=latitude,
            longitude=longitude,
            severity=severity,
            description="Synthetic incident generated by the disaster simulator (demo).",
            people_affected=people_affected,
        )
        created.append(incident)
    return created
