from dataclasses import asdict

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.core.deps import get_current_user, require_role
from app.database import get_db
from app.schemas.incident import IncidentOut
from app.schemas.simulator import (
    SimulatorStartRequest,
    SimulatorStateOut,
    SimulatorUpdateRequest,
    SpawnIncidentsRequest,
)
from app.services import alerts as alerts_service
from app.services import simulator as simulator_service

router = APIRouter(prefix="/simulator", tags=["simulator"])


@router.get("/state", response_model=SimulatorStateOut)
def get_simulator_state(_current_user=Depends(get_current_user)) -> SimulatorStateOut:
    return SimulatorStateOut(**asdict(simulator_service.get_state()))


@router.post("/start", response_model=SimulatorStateOut)
def start_simulator(
    payload: SimulatorStartRequest,
    _current_user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
) -> SimulatorStateOut:
    """The "START DISASTER" button — sets a severe preset and immediately
    raises effective hazard/accessibility on every risk zone (see
    app/services/risk_zones.py), which is what the map/home page will show
    on their next fetch. Also raises a standing area-wide alert so the
    citizen app's banner/bell light up."""
    state = simulator_service.start(
        rainfall_mm=payload.rainfall_mm,
        water_level_m=payload.water_level_m,
        road_blockage_pct=payload.road_blockage_pct,
    )
    alerts_service.upsert_simulator_alert(
        db,
        message=(
            f"Simulated severe weather over the demo area: rainfall {state.rainfall_mm:.0f} mm, "
            f"water level {state.water_level_m:.1f} m, {state.road_blockage_pct:.0f}% of roads blocked. "
            "Move away from low-lying areas and keep an emergency kit ready. "
            "(Demo alert generated by the disaster simulator.)"
        ),
    )
    return SimulatorStateOut(**asdict(state))


@router.post("/stop", response_model=SimulatorStateOut)
def stop_simulator(
    _current_user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
) -> SimulatorStateOut:
    state = simulator_service.stop()
    alerts_service.expire_simulator_alerts(db)
    return SimulatorStateOut(**asdict(state))


@router.patch("/state", response_model=SimulatorStateOut)
def update_simulator_state(
    payload: SimulatorUpdateRequest,
    _current_user=Depends(require_role("admin")),
) -> SimulatorStateOut:
    """Fine-grained slider control (rainfall/water level/road blockage)
    without necessarily flipping active — lets an operator ramp conditions
    up gradually rather than only jumping to the START DISASTER preset."""
    state = simulator_service.set_state(
        rainfall_mm=payload.rainfall_mm,
        water_level_m=payload.water_level_m,
        road_blockage_pct=payload.road_blockage_pct,
    )
    return SimulatorStateOut(**asdict(state))


@router.post("/spawn-incidents", response_model=list[IncidentOut])
def spawn_incidents(
    payload: SpawnIncidentsRequest,
    _current_user=Depends(require_role("admin")),
    db: Session = Depends(get_db),
) -> list[IncidentOut]:
    incidents = simulator_service.spawn_synthetic_incidents(
        db, count=payload.count, max_people_affected=payload.max_people_affected
    )
    return [IncidentOut.model_validate(i) for i in incidents]
